# Generated by Django 2.0.2 on 2018-04-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=20, verbose_name='领域')),
                ('areaCode', models.IntegerField(blank=True, null=True, verbose_name='领域编号')),
            ],
            options={
                'verbose_name': '领域',
                'verbose_name_plural': '领域',
                'db_table': 'areaDict',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('link', models.URLField(blank=True, verbose_name='链接')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='配图')),
                ('savetime', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
                ('origin', models.CharField(max_length=20, verbose_name='来源')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核'), (2, '已发布')], default=0, verbose_name='文章状态')),
                ('pubtime', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('isNews', models.BooleanField(choices=[(True, '是新闻'), (False, '不是新闻')], default=True, verbose_name='新闻/文章')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.AreaDict', verbose_name='领域')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookName', models.CharField(max_length=50, verbose_name='书名')),
                ('discription', models.TextField(verbose_name='书籍描述')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='书籍配图')),
                ('origin', models.CharField(max_length=20, verbose_name='来源')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('publisher', models.CharField(max_length=30, verbose_name='出版社')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核'), (2, '已发布')], default=0, verbose_name='书籍状态')),
                ('savetime', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
                ('pubtime', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.AreaDict', verbose_name='领域')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('savetime', models.DateTimeField(auto_now=True, verbose_name='保存时间')),
                ('origin', models.CharField(max_length=20, verbose_name='来源')),
                ('link', models.URLField(blank=True, verbose_name='链接')),
                ('status', models.IntegerField(choices=[(0, '未审核'), (1, '已审核'), (2, '已发布')], default=0, verbose_name='视频状态')),
                ('pubtime', models.DateField(auto_now=True, verbose_name='发布时间')),
                ('resource', models.FileField(blank=True, null=True, upload_to='', verbose_name='资源上传')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resource.AreaDict', verbose_name='领域')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
                'db_table': 'video',
            },
        ),
    ]
