# Generated by Django 2.0.4 on 2018-04-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, max_length=20000, null=True, upload_to='', verbose_name='配图'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=300, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(max_length=300, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(blank=True, max_length=200, upload_to='', verbose_name='书籍配图'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(max_length=100, verbose_name='出版社'),
        ),
    ]
