# Generated by Django 2.0.4 on 2018-05-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_book_imglink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imgLink',
            field=models.URLField(blank=True, null=True, verbose_name='图片网络链接'),
        ),
    ]
