# Generated by Django 2.0.4 on 2018-05-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_auto_20180507_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='area',
        ),
        migrations.AddField(
            model_name='article',
            name='area',
            field=models.ManyToManyField(to='resource.AreaDict', verbose_name='领域'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='area',
        ),
        migrations.AddField(
            model_name='book',
            name='area',
            field=models.ManyToManyField(to='resource.AreaDict', verbose_name='领域'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='area',
        ),
        migrations.AddField(
            model_name='video',
            name='area',
            field=models.ManyToManyField(to='resource.AreaDict', verbose_name='领域'),
        ),
    ]
