# Generated by Django 2.0.4 on 2018-05-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_auto_20180507_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=500, verbose_name='标题'),
        ),
    ]
