# Generated by Django 2.0.4 on 2018-05-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='考勤码')),
                ('maketime', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考勤码',
                'verbose_name_plural': '考勤码',
                'db_table': 'signInCode',
            },
        ),
    ]
