# Generated by Django 2.0.4 on 2018-05-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction', '0002_signincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isSigin',
            field=models.BooleanField(default=False),
        ),
    ]
