# Generated by Django 2.0.2 on 2018-04-19 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choiceText', models.CharField(max_length=100, verbose_name='选项')),
            ],
            options={
                'verbose_name': '选项',
                'verbose_name_plural': '选项',
                'db_table': 'Choice',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50, verbose_name='主题')),
                ('slice', models.FileField(upload_to='', verbose_name='课件')),
                ('upload_date', models.DateField(auto_now=True, verbose_name='上传日期')),
            ],
            options={
                'verbose_name': '课件',
                'verbose_name_plural': '课件',
                'db_table': 'meterial',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=100, verbose_name='题干')),
                ('answer', models.CharField(max_length=10, verbose_name='正解')),
            ],
            options={
                'verbose_name': '题库试题',
                'verbose_name_plural': '题库试题',
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='试卷名称')),
                ('number', models.IntegerField(default=0, verbose_name='试题数量')),
                ('create_time', models.DateField(auto_now=True, verbose_name='创建日期')),
                ('status', models.BooleanField(choices=[(False, '未发布'), (True, '已发布')], default=False, verbose_name='是否发布')),
                ('questions', models.ManyToManyField(to='inClass.Question', verbose_name='添加试题')),
            ],
            options={
                'verbose_name': '课堂测验',
                'verbose_name_plural': '课堂测验',
                'db_table': 'testpaper',
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inClass.Question', verbose_name='题干'),
        ),
    ]
