# Generated by Django 2.0.4 on 2018-05-21 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inClass', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=100, verbose_name='正解'),
        ),
    ]
